### PR TITLE
fix: add ts lib dep

### PR DESCRIPTION
**Pull request by BelfordZ**

### CODE REVIEW

**Comment by antongolub** [comment]
Hi, @BelfordZ

Could you add a bit more details about the problem?

`tslib` is already present in [`package.json`](https://github.com/qiwi/semantic-release-gh-pages-plugin/blob/master/package.json)/[yarn.lock](https://github.com/qiwi/semantic-release-gh-pages-plugin/blob/master/yarn.lock) as dev dependency.

**Comment by BelfordZ** [comment]
hey @antongolub 

I just installed this package and was getting 'cannot find module tslib' when running `node_modules/.bin/semantic-release --dry-run`

**Comment by antongolub** [comment]
Ah, I see...
```
import * as tslib_1 from "tslib";
```

**Comment by antongolub** [comment]
@BelfordZ, btw, be careful with `dry-run`. The current version does not handle this param, issue #18

**Comment by BelfordZ** [comment]
Thanks @antongolub for the quick response. <3

**Pull request closed without merging**
